version: 2
ethernets:
  eth0:
     dhcp4: false
     # default libvirt network
     addresses: [ 192.168.30.153/24 ]
     gateway4: 192.168.30.1
     nameservers:
       addresses: [ 192.168.30.17,8.8.8.8 ]
